name: Wasm CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: check files
      run: |
        git submodule update --init --recursive
        ls -alh
        ls -alh ./cimgui
        ls -alh ./cimgui/imgui

    - name: setup emsdk
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        git pull
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        cd ..
        
    - name: build
      run: |
        mkdir build
        cd build
        $(pwd)/../emsdk/upstream/emscripten/emcmake cmake ..
        make
        ls -alh
        cd ..
    
    - name: Expose as artifact
      uses: actions/upload-artifact@v2
      with:
        name: cimgui-wasm-build
        path: build/
